dmclock: ‘std::function’ has not been declared
The following error appears during make:

ceph/src/dmclock/test/test_test_client.cc:14:0:
ceph/src/dmclock/test/../sim/src/sim_recs.h:40:12: error: ‘std::function’ has not been declared
       std::function<void()> code) {

Signed-off-by: Jos Collin <jcollin@redhat.com>