common: include/ceph_features.h uses uint64_t, which is in sys/types.h
When compiling with Clang on FreeBSD there are lots of errors about
missing uint64_t:
In file included from /home/jenkins/workspace/ceph-master/src/msg/msg_types.cc:2:
In file included from /home/jenkins/workspace/ceph-master/src/msg/msg_types.h:20:
/home/jenkins/workspace/ceph-master/src/include/ceph_features.h:71:1: error: unknown type name 'uint64_t'
DEFINE_CEPH_FEATURE( 0, 1, UID)
^
/home/jenkins/workspace/ceph-master/src/include/ceph_features.h:14:15: note: expanded from macro 'DEFINE_CEPH_FEATURE'
        const static uint64_t CEPH_FEATURE_##name = (1ULL<<bit);                \

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>