cmake: cannot download boost
cmake cannot download boost because it can't loop through
the string with space separated items in boost_url variable.
so we need to declare this variable as a list

-- Using src='https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.bz2 https://download.ceph.com/qa/boost_1_79_0.tar.bz2'
CMake Error at Boost-stamp/download-Boost.cmake:162 (message):
  Each download failed!

    error: downloading 'https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.bz2 https://download.ceph.com/qa/boost_1_79_0.tar.bz2' failed
          status_code: 3
          status_string: "URL using bad/illegal format or missing URL"
          log:
          --- LOG BEGIN ---
          URL rejected: Malformed input to a URL function

  Closing connection

          --- LOG END ---

cmake version 3.29.4

According to the cmake docs for list, it is declared as semicolon
separated string using set() command:
  https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#cmake-language-lists

Example:
  set(srcs a.c b.c c.c) # sets "srcs" to "a.c;b.c;c.c"
  set(x a "b;c") # sets "x" to "a;b;c", not "a;b\;c"

Fixes: https://tracker.ceph.com/issues/66598

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>