cmake: Let's be fatal if liboath isn't present
cmake can be successful while liboath-devel isn't present leading to the following build error in rgw:

[ 12%] Building CXX object src/rgw/CMakeFiles/rgw_common.dir/rgw_rest_s3.cc.o
/home/erwan/ceph/src/rgw/rgw_rest_s3.cc:17:10: fatal error: liboath/oath.h: Aucun fichier ou dossier de ce type
 #include <liboath/oath.h>

This commit is about triggering a FATAL error when oath is missing.

Signed-off-by: Erwan Velu <erwan@redhat.com>