common/static_ptr: drop ambiguous operator==()
because in C++20, comparison operator is considered reversed also. so
drop the reversed operators.

otherwise we'd have following FTBFS:

../src/test/common/test_static_ptr.cc:64:20: error: use of overloaded operator '==' is ambiguous (with operand types 'static_ptr<base, sizeof(grandchild)>' and 'nullptr_t')
    EXPECT_FALSE(p == nullptr);
                 ~ ^  ~~~~~~~
../src/googletest/googletest/include/gtest/gtest.h:1984:25: note: expanded from macro 'EXPECT_FALSE'
  GTEST_TEST_BOOLEAN_(!(condition), #condition, true, false, \
                        ^~~~~~~~~

Signed-off-by: Kefu Chai <tchaikov@gmail.com>