cmake: check for python(\d)\.(\d+) when building boost
now that python3.10 has two digits as its minor version, we should be
able to match it.

this change fixes the build with python3.10. without this change, we'd
have

error: wrong library name 'python310' in the --with-<library> option.

when building with python3.10

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 66b1e8cecdbabd76a131dc239f6f41d5374fbd32)