Revert "Merge pull request #8346 from yuyuyu101/wip-async-clock"
This reverts commit 37117823d108dcd5145421adc0121eea75633851, reversing
changes made to 5ff4988c09ccc2af6ff72f30d053b5864a8c8e14.

This broke the build:

msg/async/Event.cc: In member function 'int EventCenter::process_time_events()':
error: msg/async/Event.cc:280:30: cannot bind 'std::basic_ostream' lvalue to 'std::basic_ostream&&'
ldout(cct, 10) << __func__ << " cur time is " << now << dendl;
^

and elsewhere...

Signed-off-by: Sage Weil <sage@redhat.com>