Revert "get_scratch_devices(): catch CommandFailedError, log "dev in use""
This reverts commit 416508de9c628c5cae1b3a7f05bb3ec0e3639bdb.

NameError: global name 'CommandFailedError' is not defined