boost: include more specific asio headers
when building with gcc5 and boost 1.66, this #include <boost/asio.hpp> fails to compile:

In file included from build/boost/include/boost/asio/impl/write.hpp:25:0,
                 from build/boost/include/boost/asio/write.hpp:927,
                 from build/boost/include/boost/asio/buffered_write_stream.hpp:29,
                 from build/boost/include/boost/asio/buffered_stream.hpp:22,
                 from build/boost/include/boost/asio.hpp:41,
                 from src/common/Graylog.h:7,
                 from src/common/LogClient.cc:20:
build/boost/include/boost/asio/detail/consuming_buffers.hpp: In member function ‘boost::asio::detail::consuming_buffers<Buffer, Buffers, Buffer_Iterator>::prepared_buffers_type boost::asio::detail::consuming_buffers<Buffer, Buffers, Buffer_Iterator>::prepare(std::size_t)’:
build/boost/include/boost/asio/detail/consuming_buffers.hpp:105:50: error: parse error in template argument list
     while (next != end && max_size > 0 && result.count < result.max_buffers)
                                                  ^
src/CMakeFiles/common-objs.dir/build.make:135: recipe for target 'src/CMakeFiles/common-objs.dir/common/LogClient.cc.o' failed

see also: https://svn.boost.org/trac10/ticket/13368

this commit targets the luminous branch specifically because the issues
doesn't reproduce on master (as we require gcc7+)

Signed-off-by: Casey Bodley <cbodley@redhat.com>