erasure-code/clay: do not set unreferenced variable
plane_count was introduced by 2a3e56b22c5b52e4834a9fd5047b3cdff7e8859f,
and presumably it is only used for debugging. let's drop it as it is not
referenced in production.

this change silences following warning:

../src/erasure-code/clay/ErasureCodeClay.cc:502:7: error: variable 'plane_count' set but not used [-Werror,-Wunused-but-set-variable]
  int plane_count = 0;
      ^

Signed-off-by: Kefu Chai <kchai@redhat.com>