include/function2.hpp: avoid using std::aligned_storage_t
std::aligned_storage_t was deprecated in C++23, now that we've switched
to C++23. let's address the warning like:

```
In file included from /mnt/igor/github/salieri11/ceph/src/osdc/Objecter.cc:15:
In file included from /mnt/igor/github/salieri11/ceph/src/osdc/Objecter.h:44:
/mnt/igor/github/salieri11/ceph/src/include/function2.hpp:962:10: error: 'aligned_storage_t' is deprecated [-Werror,-Wdeprecated-declarations]
  962 |     std::aligned_storage_t<Capacity> capacity_;
```

in this change, we

- update function2.hpp with upstream
- apply the fix to trade std::aligned_storage_t with an alignas-based
  equivalent implementation

Signed-off-by: Kefu Chai <tchaikov@gmail.com>