erasure-code/isa: don't use typename outside of template
error: erasure-code/isa/ErasureCodeIsa.h:141: using 'typename' outside of template

Signed-off-by: Sage Weil <sage@redhat.com>
(cherry picked from commit 8a193ab0338fe3500b016ede50b06a5a93f68e30)