erasure-code/clay: do not set unreferenced variable
plane_count was introduced by ae8fc89db9984e279ef71ff3875d2aab9d09a1a9,
and presumably it is only used for debugging. let's drop it as it is not
referenced in production.

this change silences following warning:

../src/erasure-code/clay/ErasureCodeClay.cc:502:7: error: variable 'plane_count' set but not used [-Werror,-Wunused-but-set-variable]
  int plane_count = 0;
      ^

Signed-off-by: Kefu Chai <kchai@redhat.com>