makefile: bump java source option from 5 to 6
this kills the errors like

error: Source option 5 is no longer supported. Use 6 or later.
error: Target option 1.5 is no longer supported. Use 1.6 or later.

Signed-off-by: Kefu Chai <kchai@redhat.com>
Conflicts:
    src/java/Makefile.am: this change is not cherry-picked from
master. as we've moved to java 8 in master. see df27ed3a .