cmake: link ceph-fuse against librt
ceph-fuse: fix error of building ceph-fuse
fix linking error of without -lrt for ceph-fuse.

error message:
```
[100%] Building CXX object src/CMakeFiles/ceph-fuse.dir/ceph_fuse.cc.o
[100%] Building CXX object src/CMakeFiles/ceph-fuse.dir/client/fuse_ll.cc.o
[100%] Linking CXX executable ../bin/ceph-fuse
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: CMakeFiles/ceph-fuse.dir/ceph_fuse.cc.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
//lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [bin/ceph-fuse] Error 1
make[2]: *** [src/CMakeFiles/ceph-fuse.dir/all] Error 2
make[1]: *** [src/CMakeFiles/ceph-fuse.dir/rule] Error 2
make: *** [ceph-fuse] Error 2
```

Signed-off-by: Yong Wang <wy7980@sina.com>