Fix ImportError: cannot import name 'environmentfilter' from 'jinja2'
Date:      Sun Apr 10 15:16925 2022 +0430

On branch fix_jinja2_version
Changes to be committed:
	modified:   admin/doc-requirements.txt
	modified:   src/pybind/mgr/dashboard/constraints.txt
	modified:   src/pybind/mgr/dashboard/constraints.txt

Signed-off-by: Ramin Najarbashi <ramin.najarbashi@gmail.com>