pybind: pickle the rados/rbd `Error` class
the Error class does not have a `message` attribute:

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/cephadm/module.py", line 774, in process
    p.evaluate()
  File "/usr/share/ceph/mgr/cephadm/module.py", line 92, in evaluate
    self.finalize(None)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 559, in finalize
    self._first_promise._finalize(result)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 301, in _finalize
    self.fail(e)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 553, in fail
    super(Completion, self).fail(e)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 347, in fail
    self._exception = e
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 195, in _exception
    self._serialized_exception_ = pickle.dumps(e) if e is not None else None
  File "rados.pyx", line 374, in rados.Error.__reduce__
AttributeError: 'ObjectNotFound' object has no attribute 'message'

Fixes: https://tracker.ceph.com/issues/46852
Signed-off-by: Michael Fritch <mfritch@suse.com>