Revert "qa/keystone: pin python-openstackclient and osc-lib"
This reverts commit 75570ce6a436fdec81f9aa720759a79d71a894f7.

the keystone task recently started failing with
> ModuleNotFoundError: No module named 'pkg_resources' because of keystone dependency

this was fixed upstream in https://github.com/openstack/osc-lib/commit/b6d1d539c875059fa64d6275011f2c6f5fe4b8e7,
but we've been pinned to an older osc-lib without this fix. the same
commit appears to resolve issues with newer 'cliff' versions which this
reverted commit also mentioned as a constraint

Fixes: https://tracker.ceph.com/issues/75041

Signed-off-by: Casey Bodley <cbodley@redhat.com>