crimson/common/smp_helpers: fix missing include
With 919953841a036c0905f3e682d757d284b830f052 introducing coroutines in
smp_helpers header, GCC 15 FTBFS with:
```
FAILED: src/crimson/CMakeFiles/crimson.dir/net/ProtocolV2.cc.o
In file included from /home/zhscn/project/ceph/src/crimson/net/io_handler.h:11,
                 from /home/zhscn/project/ceph/src/crimson/net/ProtocolV2.h:9,
                 from /home/zhscn/project/ceph/src/crimson/net/ProtocolV2.cc:4:
/home/zhscn/project/ceph/src/crimson/common/smp_helpers.h: In function ‘decltype (seastar::futurize_invoke(f)) crimson::invoke_on_all_seq(F)’:
/home/zhscn/project/ceph/src/crimson/common/smp_helpers.h:64:7: error: coroutines require a traits template; cannot find ‘std::coroutine_traits’ [-Wtemplate-body]
   64 |       co_await crimson::submit_to(core, [&f] { return seastar::futurize_invoke(f);});
      |       ^~~~~~~~
/home/zhscn/project/ceph/src/crimson/common/smp_helpers.h:64:7: note: perhaps ‘#include <coroutine>’ is missing
```

Signed-off-by: Matan Breizman <mbreizma@redhat.com>