common: use include/types.h early on, otherwise Clang will error.
This is due that FreeBSD does not have loff_t as type.
And with the wrong order of includes the standard linux typedef
is included and used.

In file included from /home/wjw/wip/src/common/buffer.cc:21:
/home/wjw/wip/src/include/buffer_raw.h:92:41: error: unknown type name 'loff_t'; did you mean 'off_t'?
    virtual int zero_copy_to_fd(int fd, loff_t *offset) {
                                        ^~~~~~
                                        off_t
/usr/include/sys/uio.h:49:17: note: 'off_t' declared here
typedef __off_t off_t;
                ^
1 error generated.

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>