tools/ceph-dencoder/common_types: remove "using namespace std"
This breaks the ARM-NEON build:

 /usr/lib/gcc/aarch64-linux-gnu/14/include/arm_neon.h:2632:31: error: reference to ‘float16_t’ is ambiguous
  2632 | __extension__ extern __inline float16_t
       |                               ^~~~~~~~~
 /usr/include/c++/14/stdfloat:40:9: note: candidates are: ‘using std::float16_t = _Float16’
    40 |   using float16_t = _Float16;
       |         ^~~~~~~~~
 /usr/lib/gcc/aarch64-linux-gnu/14/include/arm_neon.h:74:16: note:                 ‘typedef __fp16 float16_t’
    74 | typedef __fp16 float16_t;
       |                ^~~~~~~~~

Signed-off-by: Max Kellermann <max.kellermann@ionos.com>