crimson/os: fix compile error by delete packed attribute
Compiling crimson with gcc 11 get errors like:
> error: cannot bind packed field 'v.crimson::os::seastore::device_spec_t::magic' to 'long unsigned int&'

As before to fix runtime error in pr https://github.com/ceph/ceph/pull/49408 introduce the compile error.
> runtime error: reference binding to misaligned address 0x610000008395
for type 'device_type_t', which requires 4 byte alignment

As define 'enum class device_type_t {', without the underlying type (in this case, the underlying type is
an implementation-defined integral type that can represent all enumerator values), so device_type_t is
a 4 byte wide type, in func get_pos_and i is list::contiguous_appender type when encoding, and the return
value i.get_pos_add(sizeof(T)) is a byte algined address possibly, the runtime error happens in reinterpret_cast
process. We have already define 'enum class device_type_t : uint8_t {', so just delete the packed attribute
to fix the compile error.
Signed-off-by: luo rixin <luorixin@huawei.com>