cmake/modules/BuildBoost.cmake: skip unavailable feature
context-impl is moved into the per-module jam file in 1.87 which
resulted in the following error when trying to set the context-impl:

```
Boost/tools/build/src/build/feature.jam:327: in validate-feature from
module feature
error: unknown feature "<context-impl>
```

context-impl setting was brought back in 1.90 https://github.com/boostorg/context/commit/12ac945158ae3c2373ec0c888899373218aa209f

context-impl is only set in our cmake files if WITH_ASAN is on. Hence,
FTBFS, were not common so far.

Signed-off-by: Matan Breizman <mbreizma@redhat.com>