mgr/dashboard: s/hosts.clickHostTab/hosts.clickTab/
this change is a follow-up fix of
3276147049511a9a8d45d84c95154a4ec014cd83

otherwise we have following test failure:

[lint:tsc     ] cypress/integration/orchestrator/01-hosts.e2e-spec.ts(29,13): error TS2339: Property 'clickHostTab' does not exist on type 'HostsPageHelper'.

also change "host" to "hostname" to be more consistent

Fixes: https://tracker.ceph.com/issues/52645
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit a6bb0e9771eec7067ba03582583c78ded6eed8ee)