kv/RocksDBStore: use vector instead of VLA for holding slices
clang complains:

ceph/src/kv/RocksDBStore.cc:611:32: error: variable length array of
non-POD element type
      'rocksdb::Slice'
    rocksdb::Slice value_slices[to_set_bl.buffers().size()];

and i believe GCC will also complains with: -Wvla or -pedantic. as
to_set_bl.buffers().size() is not a const expr at compile time.

Signed-off-by: Kefu Chai <kchai@redhat.com>