tools/rbd_mirror: avoid forward declare CephContext in different ways
this addresses the FTBFS caused by

```
/home/jenkins/workspace/ceph-master/src/tools/rbd_mirror/PoolMetaCache.h:12:1: error: declaration conflicts with target of using declaration already in scope
struct CephContext;
^
/home/jenkins/workspace/ceph-master/src/include/common_fwd.h:10:9: note: target of using declaration
  class CephContext;
        ^
/home/jenkins/workspace/ceph-master/src/include/common_fwd.h:22:24: note: using declaration
using TOPNSPC::common::CephContext;
                       ^
In file included from /home/jenkins/workspace/ceph-master/src/tools/rbd_mirror/PoolMetaCache.cc:6:
/home/jenkins/workspace/ceph-master/src/tools/rbd_mirror/PoolMetaCache.h:19:17: error: reference to 'CephContext' is ambiguous
  PoolMetaCache(CephContext* cct)
                ^
```

Signed-off-by: Kefu Chai <kchai@redhat.com>