ceph.spec.in: Require gcc9 on openSUSE/SLE for seastar
gcc on openSUSE Leap 15.2 and SLES 15 SP2 is version 7 which does not
work with seastar. Failure is:

ceph/src/seastar/src/core/future.cc:67:50: error: \
    explicit qualification in declaration of 'seastar::future<> \
    seastar::internal::current_exception_as_future()'
      future<> internal::current_exception_as_future() noexcept;
                                                       ^~~~~~~~

Signed-off-by: Thomas Bechtold <tbechtold@suse.com>