test/fio_ceph_messenger: fix building errors
"
home/if/ceph.2/src/test/fio/fio_ceph_messenger.cc: In function ‘void
put_ceph_context()’:
/home/if/ceph.2/src/test/fio/fio_ceph_messenger.cc:144:9: error:
expected primary-expression before ‘(’ token
  144 |     dout(0) <<  ostr.str() << dendl;
      |         ^
In file included from /home/if/ceph.2/src/include/Context.h:20,
                 from /home/if/ceph.2/src/msg/Message.h:32,
                 from /home/if/ceph.2/src/msg/Messenger.h:29,
                 from
/home/if/ceph.2/src/test/fio/fio_ceph_messenger.cc:12:
/home/if/ceph.2/src/common/dout.h:190:5: error: ‘_dout_cct’ was not
declared in this scope
  190 |     _dout_cct->_log->submit_entry(std::move(_dout_e));
      \
      |     ^~~~~~~~~
/home/if/ceph.2/src/common/dout.h:216:15: note: in expansion of macro
‘dendl_impl’
  216 | #define dendl dendl_impl
....
"

Fixes: https://tracker.ceph.com/issues/77953

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

(cherry picked from commit 410238719a20799eb5a91b8456ec8ad2540a2d1e)