qa/tasks/cephfs/mount: switch to StringIO to fix TypeErrors
TypeError: cannot use a string pattern on a bytes-like object

Fixes: https://tracker.ceph.com/issues/45175
Signed-off-by: Xiubo Li <xiubli@redhat.com>
(cherry picked from commit 0631342d105575fda009e9e97b26859616be2565)

Conflicts:
	qa/tasks/cephfs/fuse_mount.py
	qa/tasks/cephfs/mount.py: drop the change not applicable to
nautilus.