qa/rgw: fix import error in tasks/swift.py
> ImportError: No module named packaging

replaces packaging.version.Version with distutils.version.LooseVersion

Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit 2dd5574cf9a5a80cc40a365675bb1e33a32c9f41)