mgr/dashboard: Taking care of deprecation warnings and other errors
1. deprecation  group is deprecated: This API is not typesafe and can result in issues with Closure Compiler renaming. Use the `FormBuilder#group` overload with `AbstractControlOptions` instead.

2. cypress/integration/rgw/users.po.ts(113,23): error TS2345: Argument of type 'void' is not assignable to parameter of type 'string'.

3. Cannot find module 'isomorphic-form-data' from 'node_modules/swagger-ui/dist/swagger-ui.js'

Fixes: https://tracker.ceph.com/issues/50268
Signed-off-by: Nizamudeen A <nia@redhat.com>
(cherry picked from commit f7d73d0420147300cbd6189620495498d27ec861)