qa/rgw: barbican and pykmip tasks upgrade pip before installing pytz
Downloading https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz (546kB)
  Complete output from command python setup.py egg_info:

          =============================DEBUG ASSISTANCE==========================
          If you are seeing an error here please try the following to
          successfully install cryptography:

          Upgrade to the latest pip and try again. This will fix errors for most
          users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          =============================DEBUG ASSISTANCE==========================

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-7fhnk5us/cryptography/setup.py", line 14, in <module>
      from setuptools_rust import RustExtension
  ModuleNotFoundError: No module named 'setuptools_rust'

Fixes: https://tracker.ceph.com/issues/52070

Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit e5a5b4e3794baf3f6bc86ed0c02ecfc8cc0f99b4)