script/redmine-upkeep: handle unknown base commits
Resolves this error:

    An unhandled error occurred during Redmine upkeep: SHA b'67473e3d4c369dd7edef15ccf0957a9c65cc562d' could not be resolved, git returned: b'67473e3d4c369dd7edef15ccf0957a9c65cc562d missing'
    Traceback (most recent call last):
      File "/home/runner/work/ceph/ceph/ceph/src/script/redmine-upkeep.py", line 1766, in main
        RU.filter_and_process_issues() # No arguments needed here anymore
      File "/home/runner/work/ceph/ceph/ceph/src/script/redmine-upkeep.py", line 1521, in filter_and_process_issues
        self._execute_filters()
      File "/home/runner/work/ceph/ceph/ceph/src/script/redmine-upkeep.py", line 1701, in _execute_filters
        self._process_issue_transformations(issue)
      File "/home/runner/work/ceph/ceph/ceph/src/script/redmine-upkeep.py", line 1370, in _process_issue_transformations
        if transform_method(issue_update):
      File "/home/runner/work/ceph/ceph/ceph/src/script/redmine-upkeep.py", line 477, in wrapper
        return func(*args, **kwargs)
      File "/home/runner/work/ceph/ceph/ceph/src/script/redmine-upkeep.py", line 910, in _transform_merged
        commit = self._get_merge_commit(issue_update)
      File "/home/runner/work/ceph/ceph/ceph/src/script/redmine-upkeep.py", line 871, in _get_merge_commit
        BASE = self.G.commit(base['sha'])
      File "/opt/hostedtoolcache/Python/3.9.25/x64/lib/python3.9/site-packages/git/repo/base.py", line 726, in commit
        return self.rev_parse(str(rev) + "^0")
      File "/opt/hostedtoolcache/Python/3.9.25/x64/lib/python3.9/site-packages/git/repo/fun.py", line 284, in rev_parse
        obj = name_to_object(repo, rev[:start])
      File "/opt/hostedtoolcache/Python/3.9.25/x64/lib/python3.9/site-packages/git/repo/fun.py", line 205, in name_to_object
        return Object.new_from_sha(repo, hex_to_bin(hexsha))
      File "/opt/hostedtoolcache/Python/3.9.25/x64/lib/python3.9/site-packages/git/objects/base.py", line 149, in new_from_sha
        oinfo = repo.odb.info(sha1)
      File "/opt/hostedtoolcache/Python/3.9.25/x64/lib/python3.9/site-packages/git/db.py", line 41, in info
        hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
      File "/opt/hostedtoolcache/Python/3.9.25/x64/lib/python3.9/site-packages/git/cmd.py", line 1679, in get_object_header
        return self.__get_object_header(cmd, ref)
      File "/opt/hostedtoolcache/Python/3.9.25/x64/lib/python3.9/site-packages/git/cmd.py", line 1663, in __get_object_header
        return self._parse_object_header(cmd.stdout.readline())
      File "/opt/hostedtoolcache/Python/3.9.25/x64/lib/python3.9/site-packages/git/cmd.py", line 1624, in _parse_object_header
        raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
    ValueError: SHA b'67473e3d4c369dd7edef15ccf0957a9c65cc562d' could not be resolved, git returned: b'67473e3d4c369dd7edef15ccf0957a9c65cc562d missing'

caused by a merge on a working integration branch.

Signed-off-by: Patrick Donnelly <pdonnell@ibm.com>