mgr/cephadm: protections for self.daemons
RuntimeError: dictionary changed size during iteration can
occur for self.daemons, this commit adds protections so
this error cannot happen. Also for self._tmp_daemons.

Signed-off-by: Timothy Q Nguyen <timqn22@gmail.com>
(cherry picked from commit a0e9c3e8b94ced150b6af591ea1fee248f52e1ae)