squid: rgw/s3-tests: s3: disable checksum calculation for test_object_create_bad_contentlength_negative
if tls is enabled, boto will switch to STREAMING-UNSIGNED-PAYLOAD-TRAILER
and omit the provided content-length header. this leads to test failure:

> ________________ test_object_create_bad_contentlength_negative _________________
>       e = assert_raises(ClientError, client.put_object, Bucket=bucket_name, Key=key_name, ContentLength=-1)
> AssertionError: ClientError not raised

Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit a40c28fcc35a363f3320de9ce6586c4ca7fe09ef)

Conflicts:
	src/test/rgw/s3-tests/s3tests_boto3/functional/test_headers.py
 - Renamed
 - upstream has new imports for sigv4 tests

Assisted-by: Claude Opus 5 <noreply@anthropic.com>
Signed-off-by: Adam C. Emerson <aemerson@redhat.com>