mgr/dashboard: s/hosts.clickHostTab/hosts.clickTab/
this change is a follow-up fix of
7a2fabd5d5f274b0fe1c80ca75223c9c69ac1169

otherwise we have following test failure:

[lint:tsc     ] cypress/integration/orchestrator/01-hosts.e2e-spec.ts(29,13): error TS2339: Property 'clickHostTab' does not exist on type 'HostsPageHelper'.

also change "host" to "hostname" to be more consistent

Fixes: https://tracker.ceph.com/issues/52645
Signed-off-by: Kefu Chai <tchaikov@gmail.com>