cmake: enlist libceph-common as json_spirit's depedency.
Before the commit the library was using symbols, like `ceph_assert`
(see ddfcec5f8756bb66c68ef6b18bf9dd3ea046838d), from `common` but
without enlisting the dependency. This was the reason for a FTBFS:

```
[ 57%] Linking CXX executable ../../bin/ceph_scratchtool
cd /work/ceph-2/build/src/tools && /usr/bin/cmake -E cmake_link_script CMakeFiles/ceph_scratchtool.dir/link.txt --verbose=1
/usr/bin/c++  -O2 -g -DNDEBUG   -rdynamic CMakeFiles/ceph_scratchtool.dir/scratchtool.c.o  -o ../../bin/ceph_scratchtool -Wl,-rpath,/work/ceph-2/build/lib: ../../lib/librados.so.2.0.0 ../../lib/libglobal.a ../../lib/libceph-common.so.2 ../../lib/libjson_spirit.a ../../lib/libcommon_utf8.a ../../lib/liberasure_code.a ../../lib/libcrc32.a ../../lib/libarch.a ../../boost/lib/libboost_thread.a ../../boost/lib/libboost_chrono.a ../../boost/lib/libboost_atomic.a ../../boost/lib/libboost_system.a ../../boost/lib/libboost_random.a ../../boost/lib/libboost_program_options.a ../../boost/lib/libboost_date_time.a ../../boost/lib/libboost_iostreams.a ../../boost/lib/libboost_regex.a ../../lib/libfmt.a -lstdc++fs /usr/lib/x86_64-linux-gnu/libblkid.so /usr/lib/x86_64-linux-gnu/libcrypto.so -lpthread /usr/lib/x86_64-linux-gnu/libudev.so /usr/lib/libibverbs.so /usr/lib/x86_64-linux-gnu/librdmacm.so /usr/lib/x86_64-linux-gnu/libz.so -ldl /usr/lib/x86_64-linux-gnu/librt.so -lresolv
/usr/bin/ld: ../../lib/librados.so.2.0.0: undefined reference to symbol '_ZN4ceph18__ceph_assert_failERKNS_11assert_dataE'
../../lib/libceph-common.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/tools/CMakeFiles/ceph_scratchtool.dir/build.make:108: recipe for target 'bin/ceph_scratchtool' failed
```

```
$ nm ../../lib/libjson_spirit.a | grep _ZN4ceph18__ceph_assert_failERKNS_11assert_dataE
                 U _ZN4ceph18__ceph_assert_failERKNS_11assert_dataE
                 U _ZN4ceph18__ceph_assert_failERKNS_11assert_dataE
```

This commit fixes that.

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>