build: fix linking problem around the replayer tool
```
[2/634] Linking CXX executable bin/replayer
FAILED: bin/replayer
: && /opt/rh/gcc-toolset-11/root/usr/bin/g++ -O2 -g -DNDEBUG -rdynamic -pie src/test/objectstore/allocsim/CMakeFiles/replayer.dir/ops_replayer.cc.o -o bin/replayer  -Wl,-rpath,/home/rzarzynski/ceph1/build/lib  l
ib/libfmt.a  lib/librados.so.2.0.0  boost/lib/libboost_program_options.a  lib/libfmt.a  boost/lib/libboost_program_options.a  -Wl,-rpath-link,/home/rzarzynski/ceph1/build/lib  -Wl,--as-needed -latomic && :
/opt/rh/gcc-toolset-11/root/usr/bin/ld: src/test/objectstore/allocsim/CMakeFiles/replayer.dir/ops_replayer.cc.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>