rgw: fix ambiguous flat_set::insert with Boost 1.91
feature_less uses `is_transparent`, which causes Boost 1.91's
transparent insert(const_iterator, K&&) overload to compete with
the range insert(InputIterator, InputIterator) overload when the
iterators come from a flat_set with the same comparator:

```
/home/kefu/dev/ceph/src/rgw/rgw_zone.cc: In function ‘int rgw::add_zone_to_group(const DoutPrefixProvider*, RGWZoneGroup&, const RGWZoneParams&, const bool*, const bool*, const std::__cxx11::list<std::__cxx11::basic_string<char> >&, const std::string*, c
onst bool*, const std::__cxx11::list<std::__cxx11::basic_string<char> >&, const std::__cxx11::list<std::__cxx11::basic_string<char> >&, const std::string*, std::optional<int>, const zone_features::set&, const zone_features::set&)’:
/home/kefu/dev/ceph/src/rgw/rgw_zone.cc:1042:33: error: call of overloaded ‘insert(boost::container::dtl::flat_tree<std::__cxx11::basic_string<char>, boost::move_detail::identity<std::__cxx11::basic_string<char> >, rgw::zone_features::feature_less, void>
::const_iterator, boost::container::dtl::flat_tree<std::__cxx11::basic_string<char>, boost::move_detail::identity<std::__cxx11::basic_string<char> >, rgw::zone_features::feature_less, void>::const_iterator)’ is ambiguous
 1042 |   zone.supported_features.insert(enable_features.begin(),
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
 1043 |       enable_features.end());
      |       ~~~~~~~~~~~~~~~~~~~~~~
  • there are 2 candidates
In file included from /home/kefu/dev/ceph/src/include/denc.h:40,
                 from /home/kefu/dev/ceph/src/include/encoding.h:44,
                 from /home/kefu/dev/ceph/src/include/uuid.h:9,
                 from /home/kefu/dev/ceph/src/include/types.h:23,
                 from /home/kefu/dev/ceph/src/rgw/rgw_zone_types.h:31,
                 from /home/kefu/dev/ceph/src/rgw/rgw_zone.h:7,
                 from /home/kefu/dev/ceph/src/rgw/rgw_zone.cc:10:
    • candidate 1: ‘typename boost::container::dtl::enable_if_transparent<Compare, K, typename boost::container::dtl::flat_tree<Key, boost::move_detail::identity<T>, Compare, AllocatorOrContainer>::sequence_type::iterator>::type boost::container::flat_se
t<Key, Compare, Allocator>::insert(const_iterator, K&&) [with K = boost::container::vec_iterator<std::__cxx11::basic_string<char>*, true>; Key = std::__cxx11::basic_string<char>; Compare = rgw::zone_features::feature_less; AllocatorOrContainer = void; ty
pename boost::container::dtl::enable_if_transparent<Compare, K, typename boost::container::dtl::flat_tree<Key, boost::move_detail::identity<T>, Compare, AllocatorOrContainer>::sequence_type::iterator>::type = boost::container::vec_iterator<std::__cxx11::
basic_string<char>*, false>; typename boost::container::dtl::flat_tree<Key, boost::move_detail::identity<T>, Compare, AllocatorOrContainer>::sequence_type::iterator = boost::container::vec_iterator<std::__cxx11::basic_string<char>*, false>; typename boos
t::container::dtl::flat_tree<Key, boost::move_detail::identity<T>, Compare, AllocatorOrContainer>::sequence_type = boost::container::vector<std::__cxx11::basic_string<char>, void, void>; const_iterator = boost::container::vec_iterator<std::__cxx11::basic
_string<char>*, true>]’
      /usr/include/boost/container/flat_set.hpp:744:7:
        744 |       insert(const_iterator p, K &&x)
            |       ^~~~~~
    • candidate 2: ‘void boost::container::flat_set<Key, Compare, Allocator>::insert(InputIterator, InputIterator) [with InputIterator = boost::container::vec_iterator<std::__cxx11::basic_string<char>*, true>; Key = std::__cxx11::basic_string<char>; Comp
are = rgw::zone_features::feature_less; AllocatorOrContainer = void]’
      /usr/include/boost/container/flat_set.hpp:764:16:
        764 |    inline void insert(InputIterator first, InputIterator last)
            |                ^~~~~~
```

Use std::copy with std::inserter to perform a range insert via
the unambiguous insert(const_iterator, const value_type&) overload.

Signed-off-by: Kefu Chai <k.chai@proxmox.com>