common/async: avoid using std::aligned_storage_t
std::aligned_storage_t was deprecated in C++23, now that we've switched
to C++23. let's address the warning like:

```
In file included from /mnt/igor/github/salieri11/ceph/src/osdc/Objecter.cc:60:
/mnt/igor/github/salieri11/ceph/src/common/async/waiter.h:141:8: error: 'aligned_storage_t' is deprecated [-Werror,-Wdeprecated-declarations]
  141 |   std::aligned_storage_t<sizeof(Ret)> ret;
      |        ^
/opt/rh/gcc-toolset-14/root//usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/type_traits:2699:29: note: 'aligned_storage_t' has been explicitly marked deprecated here
 2699 |     using aligned_storage_t _GLIBCXX23_DEPRECATED = typename aligned_storage<_Len, _Align>::type;
      |                             ^
```

Signed-off-by: Kefu Chai <tchaikov@gmail.com>