common: fix missing constructor WorkQueue with time_t
Otherwise clang/FreeBSD complains:

In file included from /home/jenkins/workspace/ceph-master-compile/src/os/ObjectStore.h:26:
/home/jenkins/workspace/ceph-master-compile/src/common/WorkQueue.h:150:9: error: no matching constructor for initialization of 'ThreadPool::WorkQueue_'
      : WorkQueue_(std::move(n), ti, sti), pool(p) {
        ^          ~~~~~~~~~~~~~~~~~~~~~
/home/jenkins/workspace/ceph-master-compile/src/common/WorkQueue.h:81:5: note: candidate constructor not viable: no known conversion from 'time_t' (aka 'long') to 'ceph::timespan' (aka 'duration<unsigned long, ratio<1LL, 1000000000LL> >') for 2nd argument
    WorkQueue_(std::string n, ceph::timespan ti, ceph::timespan sti)
    ^
/home/jenkins/workspace/ceph-master-compile/src/common/WorkQueue.h:77:10: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
  struct WorkQueue_ {
         ^
1 warning and 1 error generated.

fixes: https://github.com/ceph/ceph/pull/36405
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>