mgr/BaseMgrModule: Conditionalize python27 PyInt_Check
Building in a 3.6 only environment gives:
/home/jenkins/workspace/ceph-master36/src/mgr/BaseMgrModule.cc:308:13: error: use of undeclared identifier 'PyInt_Check'
        } else if (PyInt_Check(v)) {
                   ^
1 error generated.

But looks like PyLong_Check would also work for ints on 3.6:
  https://docs.python.org/3.6/c-api/long.html?highlight=pylong_check

int PyLong_Check(PyObject *p)
    Return true if its argument is a PyLongObject or a subtype of PyLongObject.

Introduced by: https://github.com/ceph/ceph/pull/29806

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>