python-common: fix mypy failure in NVMEoF service spec
Locally, mypy was complaining

```
ceph/deployment/service_spec.py: note: In member "validate" of class "NvmeofServiceSpec":
ceph/deployment/service_spec.py:1497: error: Unsupported operand types for > ("float" and "None")  [operator]
ceph/deployment/service_spec.py:1497: note: Left operand is of type "Optional[float]"
ceph/deployment/service_spec.py:1500: error: Unsupported operand types for > ("int" and "None")  [operator]
ceph/deployment/service_spec.py:1500: note: Left operand is of type "Optional[int]"
```

I'm unsure why those errors didn't show up in the CI,
but they make sense to me, so why not fix them.

Signed-off-by: Adam King <adking@redhat.com>
(cherry picked from commit 1841c4117829f91ec17034acb47494e17085171c)