compressor: fix rpmbuild on RHEL-8
When building rpms on latest RHEL-8.6:

    [  0%] Building CXX object src/compressor/CMakeFiles/compressor_objs.dir/Compressor.cc.o
    In file included from /d/ceph-build/ceph-17.2.3-0-dff484dfc9e/src/common/config_values.h:59,
                     from /d/ceph-build/ceph-17.2.3-0-dff484dfc9e/src/common/config.h:27,
                     from /d/ceph-build/ceph-17.2.3-0-dff484dfc9e/src/common/config_proxy.h:6,
                     from /d/ceph-build/ceph-17.2.3-0-dff484dfc9e/src/common/ceph_context.h:41,
                     from /d/ceph-build/ceph-17.2.3-0-dff484dfc9e/src/compressor/Compressor.cc:23:
    /d/ceph-build/ceph-17.2.3-0-dff484dfc9e/src/common/options/legacy_config_opts.h:1:10: fatal error: global_legacy_options.h: No such file or directory
        1 | #include "global_legacy_options.h"
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [src/compressor/CMakeFiles/compressor_objs.dir/build.make:76: src/compressor/CMakeFiles/compressor_objs.dir/Compressor.cc.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:7964: src/compressor/CMakeFiles/compressor_objs.dir/all] Error 2
    make: *** [Makefile:146: all] Error 2
    error: Bad exit status from /var/tmp/rpm-tmp.1CBUsC (%build)

    RPM build errors:
        Bad exit status from /var/tmp/rpm-tmp.1CBUsC (%build)

Solution: add legacy-option-headers dependency to compressor_objs.

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>
(cherry picked from commit 3b3da64d741960e2ecb217c1990142f4a88f2fa3)