msg: Add missing <optional> header file.
Clang complains:
```
In file included from /home/jenkins/workspace/ceph-master-compile/src/msg/async/compression_onwire.cc:4:
/home/jenkins/workspace/ceph-master-compile/src/msg/async/compression_onwire.h:40:5: error: no template named 'optional' in namespace 'std'; did you mean 'boost::optional'?
    std::optional<ceph::bufferlist> decompress(const ceph::bufferlist &input);
    ^~~~~~~~~~~~~
    boost::optional
```

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>