mds: wake up lock waiters after forcibly changing lock state
commit df79944a "mds: cleanup unneeded client_snap_caps when
splitting snap inode" is incomplete.

Fixes: http://tracker.ceph.com/issues/39987
Signed-off-by: "Yan, Zheng" <zyan@redhat.com>
(cherry picked from commit 0a1e92abf1cfc8bddf526cbf5bceea7b854dcfe8)

Conflicts:
    src/mds/MDCache.cc
- in mimic, "error: 'vec' is not a member of 'MDSContext'"
  addressed by declaring finished as list<MDSInternalContextBase*> instead of
  MDSContext::vec