common: fix missing <cstdio> include
On FreeBSD snprinf() lives in <cstdio>.

/home/jenkins/workspace/ceph-master36/src/common/compat.cc:202:5: error: use of undeclared identifier 'snprintf'
    snprintf(buf, buflen, "Unknown error %d", errnum);
    ^
1 error generated.

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>