LocalCephManager.admin_socket: add timeout kwarg
This fixes "TypeError: admin_socket() got an unexpected keyword argument
'timeout'". The value is never used.

Signed-off-by: Zack Cerza <zack@redhat.com>
(cherry picked from commit b134972035a383a34f4bbe4059591c889d28a8c0)
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>