mgr/cephadm: fix broken "already in use" exception message
Fixes:

```
orchestrator._interface.OrchestratorValidationError: ('name %s already in use', 'b')
```

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
(cherry picked from commit 9a45c39c68956c87e55ec4cce90a7bb4df524b97)