ceph.spec.in: python-kubernetes broken on rhel
Error: Package: python2-kubernetes-8.0.0-6.el7.noarch (epel)
           Requires: python-adal

Signed-off-by: Sage Weil <sage@redhat.com>