include: xlist: Fix Clang error for missing string
Clang complains:
home/jenkins/workspace/ceph-master/src/include/xlist.h:210:13: error: invalid operands to binary exp
ression ('std::ostream' (aka 'basic_ostream<char>') and 'const char *')
        oss << ", ";
        ~~~ ^  ~~~~
1 error generated.

include ostream to fix Clang error

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>