qa: switch back to git protocol for qemu-xfstests
As noted in commit 1f8c61217e23 ("qa: switch to https protocol for
repos' server"), git.ceph.com mirror doesn't make git:// available
anymore.  However, run_xfstests-obsolete.sh has "obsolete" in its
name for a reason -- due to an ancient execution environment, git://
is the only viable option:

  $ git clone https://git.ceph.com/xfstests-dev.git
  Cloning into 'xfstests-dev'...
  error: gnutls_handshake() failed: A TLS fatal alert has been received. while accessing https://git.ceph.com/xfstests-dev.git/info/refs
  fatal: HTTP request failed

Ditch git.ceph.com mirror for now.

Signed-off-by: Ilya Dryomov <idryomov@gmail.com>