rbd/bench: include used headers
should help with fixing following failure:

src/tools/rbd/action/Bench.cc:20:26: error: aggregate 'std::atomic<bool>
terminating' has incomplete type and cannot be defined

Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit f16ac13c13eceed7adb5a4a04a3372b921e63031)