cmake: fix the tracing header dependencies
in aa679df, we move librados.cc into a separated obj target. this broken
the dependency from librados.o to its tracing header. we need to update
it accordingly.

this change fixes the following compilation error:
```
/var/ceph/ceph/src/librados/librados.cc:47:30: fatal error:
tracing/librados.h: No such file or directory
 #include "tracing/librados.h"
                              ^
compilation terminated.
```

Signed-off-by: Kefu Chai <kchai@redhat.com>