ceph.spec.in: Remove rgw-restore-bucket-index.8* from packaging
Fix RPM build failure caused by missing manpage in reef branch.

In commit bbe80059, we backported 8d0ec766 to reef but incorrectly
included `%{_mandir}/man8/rgw-restore-bucket-index.8*` in the package
files section. The original commit 8d0ec766 only added
`%{_mandir}/man8/rgw-gap-list.8*`, and the rgw-restore-bucket-index
manpage is not built in the reef branch.

This caused RPM build failures because rpmbuild requires all packaged
files to exist in the build directory:

```
error: File not found: /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/18.2.7-518-ge3d44f43/rpm/el9/BUILDROOT/ceph-18.2.7-518.ge3d44f43.el9.x86_64/usr/share/man/man8/rgw-restore-bucket-index.8*
```

In this change, we remove `%{_mandir}/man8/rgw-restore-bucket-index.8*`
from the ceph-common package files section to resolve this issue.

Note: This is a reef-specific fix addressing a backport issue and
is not cherry-picked from master.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>