test/fio: fix a compiler error.
Met the following bug when -DWITH_FIO=ON:
/home/src/test/fio/fio_ceph_messenger.cc:217:5: error: ‘require_authorizer’ was not declared in this scope
     require_authorizer = false;
This bug introduce by 0d5a3df3174f1a051 which omit this.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>