tests: TEST_crush_reject_empty must not run a mon
Back in Hammer, the osd-crush.sh individual tests did not run the
monitor, it was taken care of by the run() function. An attempt to run
another mon fails with:

error: IO lock testdir/osd-crush/a/store.db/LOCK: Resource temporarily
unavailable

This problem was introduced by cc1cc033930e8690a57674e842a003f6bbc7a242
from https://github.com/ceph/ceph/pull/4936

http://tracker.ceph.com/issues/11975 Refs: #11975

Signed-off-by: Loic Dachary <ldachary@redhat.com>