script: install locales and iproute2 in build containers
Test scripts like vstart_runner.py expect en_US.UTF-8 locale and the
ip command to be available in the container environment. Without these,
tests fail with:

  ./run-backend-api-tests.sh: line 179: warning: setlocale: LC_ALL:
  cannot change locale (en_US.UTF-8): No such file or directory

  /bin/bash: line 1: ip: command not found

  File "/ceph/qa/tasks/cephfs/mount.py", line 96, in cleanup_stale_netnses_and_bridge
    p = remote.run(args=['ip', 'netns', 'list'],
  ...
  teuthology.exceptions.CommandFailedError: Command failed with status 127: 'ip netns list'

Add the locales and iproute2 packages to Ubuntu/Debian build containers
and generate en_US.UTF-8 locale during container setup.

Signed-off-by: Kefu Chai <k.chai@proxmox.com>
(cherry picked from commit 57a6c43917ee82697584c384acdd3bc691a4ab8c)