cephadm: require fsid if name contains a daemon id
$ cephadm shell --name mon.123
INFO:cephadm:Found fsids []
Traceback (most recent call last):
  File "./cephadm", line 2805, in <module>
    r = args.func()
  File "./cephadm", line 646, in _infer_fsid
    return func()
  File "./cephadm", line 1992, in command_shell
    no_config=True if args.config else False)
  File "./cephadm", line 1009, in get_container_mounts
    data_dir = get_data_dir(fsid, daemon_type, daemon_id)
  File "./cephadm", line 670, in get_data_dir
    return os.path.join(args.data_dir, fsid, '%s.%s' % (t, n))
  File "/usr/lib64/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

Signed-off-by: Michael Fritch <mfritch@suse.com>