include/cpp-tree: add missing ostream
FreeBSD/stdlib requires ostream:
/home/jenkins/workspace/ceph-master/src/include/cpp-btree/btree.h:2537:10: error: invalid operands to binary expression ('std::ostream' (aka 'basic_ostream<char>') and 'const char [3]')
      os << "  ";
      ~~ ^  ~~~~
/usr/include/c++/v1/type_traits:4034:3: note: candidate function template not viable: cannot convert argument of incomplete type 'std::ostream' (aka 'basic_ostream<char>') to 'std::byte' for 1st argument
  operator<< (byte  __lhs, _Integer __shift) noexcept
  ^
/usr/include/c++/v1/memory:5264:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-2>' against 'char const[3]'
operator<<(basic_ostream<_CharT, _Traits>& __os, shared_ptr<_Yp> const& __p);
^
/usr/include/c++/v1/string:4244:1: note: candidate template ignored: could not match 'basic_string<type-parameter-0-0, type-parameter-0-1, type-parameter-0-2>' against 'char const[3]'
operator<<(basic_ostream<_CharT, _Traits>& __os,
^
1 error generated.

Fixes: https://github.com/ceph/ceph/pull/32443
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>