cmake: fix librados compiling error
The build error happened with the following message:
    ```
    /var/ceph/ceph/src/librados/librados.cc:47:30: fatal error:
    tracing/librados.h: No such file or directory
     #include "tracing/librados.h"
                                  ^
    compilation terminated.
    ```
Actually, this issue was fixed by commit: 5e03ff098166 (
"cmake: fix the tracing header dependencies"). However,
it comes up again becuase of this commit: 0a717593c0c3 (
"cmake: let librados_api_obj depend on librados-tp"), which
forgets to replace "rados-tp" with "librados-tp". So, complete
this change accordingly.

Signed-off-by: Eric Ren <zren@suse.com>