ceph-volume/tests: fix an issue with rpm
Typical error seen in the CI:

```
error: /var/cache/dnf/baseos-00fe51d07def85f0/packages/kernel-core-4.18.0-483.el8.x86_64.rpm: signature hdr data: BAD, no. of bytes(459772) out of range
```

Upgrading `rpm` fixes this issue.

Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>
(cherry picked from commit 05aa334b96ed8a8c8497047bc26da64ee3a3d1fa)