pybind: fix cephfs.OSError initialization
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cephfs.pyx", line 672, in cephfs.LibCephFS.open (/home/zhyan/Ceph/ceph-2/build/src/pybind/cephfs/pyrex/cephfs.c:10160)
  File "cephfs.pyx", line 155, in cephfs.OSError.__init__ (/home/zhyan/Ceph/ceph-2/build/src/pybind/cephfs/pyrex/cephfs.c:1889)
TypeError: __init__() takes exactly 3 positional arguments (2 given)

Signed-off-by: "Yan, Zheng" <zyan@redhat.com>
(cherry picked from commit e6493f64ba4592b8dca54ece4464efa6c7f331a7)