cmake: fix compiler error when -DALLOCATOR=jemalloc.
If -DALLOCATOR=jemalloc, met the following error messages:
>>../../rocksdb/librocksdb.a(malloc_stats.cc.o): In function `rocksdb::DumpMallocStats(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
>>/home/ceph/src/rocksdb/db/malloc_stats.cc:51: undefined reference to `malloc_stats_print'
>>collect2: error: ld returned 1 exit status
>>src/test/ObjectMap/CMakeFiles/ceph_test_keyvaluedb_atomicity.dir/build.make:148: recipe for target 'bin/ceph_test_keyvaluedb_atomicity' failed
>>make[2]: *** [bin/ceph_test_keyvaluedb_atomicity] Error 1
>>CMakeFiles/Makefile2:17699: recipe for target 'src/test/ObjectMap/CMakeFiles/ceph_test_keyvaluedb_atomicity.dir/all' failed
>>make[1]: *** [src/test/ObjectMap/CMakeFiles/ceph_test_keyvaluedb_atomicity.dir/all] Error 2
>>make[1]: *** Waiting for unfinished jobs....

This bug introduced by 2e012870315e5a08e.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>