mgr/cephadm: clean-up service module type checking
mypy cast to avoid:

cephadm/module.py: note: In member "_config_fn" of class "CephadmOrchestrator":
cephadm/module.py:1797: error: Incompatible return value type (got "Optional[function]", expected "Optional[Callable[[ServiceSpec], None]]")

Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit 502c574c36f49947cb7a501cafd5530455451773)