rgw/posix: std::ignore return value of write()
/ceph/src/rgw/driver/posix/notify.h: In member function 'void file::listing::Inotify::signal_shutdown()':
/ceph/src/rgw/driver/posix/notify.h:215:19: error: ignoring return value of 'ssize_t write(int, const void*, size_t)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
  215 |       (void) write(efd, &msg, sizeof(uint64_t));
      |              ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Fixes: https://tracker.ceph.com/issues/69241

Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit a2ebc00a56fcffc57b04fad1e5d134f75ae753eb)