common/ceph_time: move operator<<() into ceph::details namespace
in bench_cls_fifo.cc, we use

fmt::print(std::cout, "{}\t{}\n", entry.marker, entry.mtime)

to print out the `entry.mtime` using libfmt, but clang fails to compile
like:

fmt/core.h:1016:5: error: static_assert failed due to requirement 'formattable' "Cannot format argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/lat\
est/api.html#formatting-user-defined-types"
    static_assert(
    ^
...
src/test/cls_fifo/bench_cls_fifo.cc:447:7: note: in instantiation of function template specialization 'fmt::v6::print<char [7], const std::__cxx11::basic_string<char,
std::char_traits<ch\
ar>, std::allocator<char> > &, const std::chrono::time_point<ceph::time_detail::real_clock, std::chrono::duration<unsigned long, std::ratio<1, 1000000000> > > &, char>' requested here
        fmt::print(std::cout, "{}\t{}\n", entry.marker, entry.mtime);
             ^

it's due to ADL. instead of looking up in the `ceph` namespace where the alias
of `ceph::real_clock` is defined for `operator<<`, Clang tries to find it in
`ceph::time_detail`. and it fails. as the `operator<<` templates are defined in
`ceph` namespace.

in this change, `operator<<` templates are defined in `ceph::time_detail`, and
they are exposed using `using` in `ceph` namespace, to make sure the ADL can
also find them if the compiler thinks that the alias belong to the namespace
where they are defined.

Signed-off-by: Kefu Chai <kchai@redhat.com>