neorados/cls/fifo/detail/fifo: include strtol.h
https://github.com/ceph/ceph/commit/a2d26647c011274b61805f8ac17c3422e9b9b63c

ftbfs:
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/neorados/cls/fifo/detail/fifo.h:630:14: error: no member named 'parse' in namespace 'ceph'; did you mean 'pause'?
  630 |     auto n = ceph::parse<decltype(m.num)>(num);
      |              ^~~~~~~~~~~
```

Signed-off-by: Matan Breizman <mbreizma@redhat.com>
(cherry picked from commit 3df1133c17b174c27c250cf7ac018199cc40b15b)
Signed-off-by: Adam C. Emerson <aemerson@redhat.com>