cephadm: remove useless printout during ingress deployment
With the parallel deployment we actually need to make sure
we don't print anything to stdout which this was doing. It's
also just not a useful printout.

2025-06-16T17:28:11.637178+0000 mgr.vm-01.tqkwuq [DBG] out: UUUUU <function extract_uid_gid at 0x7f6bc5ce0f70>
{"haproxy.nfs.foo.vm-00.mesmdl": 0}
2025-06-16T17:28:11.637192+0000 mgr.vm-01.tqkwuq [DBG] err: Reconfig daemon haproxy.nfs.foo.vm-00.mesmdl ...
Write file: /var/lib/ceph/ecd9b924-4ac9-11f0-8e5f-5254006acf2d/haproxy.nfs.foo.vm-00.mesmdl/haproxy/haproxy.cfg
2025-06-16T17:28:11.639616+0000 mgr.vm-01.tqkwuq [ERR] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/cephadm/serve.py", line 1342, in _check_daemons
    self.mgr._daemon_action(daemon_spec, action=action)
  File "/usr/share/ceph/mgr/cephadm/module.py", line 2627, in _daemon_action
    successes, failures = self.wait_async(
  File "/usr/share/ceph/mgr/cephadm/module.py", line 806, in wait_async
    return self.event_loop.get_result(coro, timeout)
  File "/usr/share/ceph/mgr/cephadm/ssh.py", line 136, in get_result
    return future.result(timeout)
  File "/lib64/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/share/ceph/mgr/cephadm/serve.py", line 1631, in _create_daemon
    results: Dict[str, int] = json.loads(out[0])
  File "/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Signed-off-by: Adam King <adking@redhat.com>