win32_deps_build: avoid pip
We're currently installing cython with pip when using Ubuntu
to cross compile Ceph for Windows. This can fail with recent
Python versions if attempting to use the global env:

  error: externally-managed-environment

  × This environment is externally managed
  ╰─> To install Python packages system-wide, try apt install
      python3-xyz, where xyz is the package you are trying to
      install.

Cython isn't really needed by the Windows build so we can go
ahead and drop it. We were hoping to use the Python bindings
on Windows, however Python extensions can't be cross compiled.

We're no longer using pip either, so we're dropping the dependency.
g++ was getting installed as a pip dependency, so we'll have to
include that instead. Note that g++ is used when building the boost
b2 tool.

While at it, we'll also ensure that git is installed.

Fixes: https://tracker.ceph.com/issues/59354

Signed-off-by: Lucian Petrut <lpetrut@cloudbasesolutions.com>
(cherry picked from commit 041618ea9b9b09b8dcf00170417b246eaaabce8b)

Conflicts:
	win32_deps_build.sh
        -> commit 4954fe1 ("win32: add rhel option") not in quincy

[1] https://github.com/ceph/ceph/commit/4954fe19e5594ca5cac1d639fcfa49941abbbfa9