libcephfs: add missing declaration of ceph_getaddrs()
this function was added by 38ececc225. but the declaration was not added
to the header file.

this change silences following warning:

build/src/pybind/cephfs/pyrex/cephfs.c:6647:25: warning: implicit declaration of function 'ceph_getaddrs'; did you mean 'ceph_getxattr'? [-Wimplicit-function-declaration]
           __pyx_v_ret = ceph_getaddrs(__pyx_v_self->cluster, (&__pyx_v_addrs));
                         ^~~~~~~~~~~~~
                         ceph_getxattr

Signed-off-by: Kefu Chai <kchai@redhat.com>