mgr/orch: pass `inbuf` to add/apply (mds, rgw, nfs)
$ ceph orch apply mds a -i mds.yaml
TypeError: _apply_mds() got an unexpected keyword argument 'inbuf'

Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit f285bbf5428d1233917ec66e68b30517bd437a76)