Added single check to avoid duplication. Included few more commands.
Signed-off-by: Shilpa Jagannath <smanjara@redhat.com>
(cherry picked from commit 14c3b4b3ebb6ef2fc44d24f8020beb2977c8e46e)

Conflicts:
        src/rgw/rgw_admin.cc
- cherry-pick was clean, but there was a build failure "error: 'class RGWRados'
has no member named 'svc'", which was fixed by making the following change:

-  bool non_master_cmd = (!store->svc.zone->is_meta_master() && !yes_i_really_mean_it);
+  bool non_master_cmd = (!store->is_meta_master() && !yes_i_really_mean_it);

- drop OPT_MFA_CREATE, OPT_MFA_REMOVE, and OPT_MFA_RESYNC which were added
  post-luminous (by 3ab463f9f538a08fd11db2b654004449994dd0fe)