cephadm: still set keep_container_info key in CoreStatusUpdater when cinfo is None
When testing an unrelated thing with rm-cluster cleaning up
OSD devices, I was hitting

```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/sbin/cephadm/__main__.py", line 5400, in <module>
  File "/usr/sbin/cephadm/__main__.py", line 5388, in main
  File "/usr/sbin/cephadm/__main__.py", line 3996, in command_rm_cluster
  File "/usr/sbin/cephadm/__main__.py", line 4034, in _rm_cluster
  File "/usr/sbin/cephadm/__main__.py", line 428, in _infer_image
  File "/usr/sbin/cephadm/cephadmlib/container_lookup.py", line 127, in infer_local_ceph_image
  File "/usr/sbin/cephadm/cephadmlib/container_lookup.py", line 128, in <listcomp>
KeyError: '_container_info'
```

which appears to have been caused by the CoreStatusUpdater only
setting the "keep_container_info" key entry when the container
info it gets back from get_container_stats is not None. This
patch has it set that key entry even when the container info
is None, and updates infer_local_ceph_image to be able to
handle the container info at that entry being None as well.

Signed-off-by: Adam King <adking@redhat.com>