rgw/beast: fix atomic_load_explicit typo
typo from d8a3f3e2c5ae4d586fffdb12426c836b659c99cd was not detected
during qa. this causes a compilation failure on ubuntu jammy:

src/rgw/rgw_asio_frontend.cc:1193:31: error: 'atomic_load_excplicit' is not a member of 'std'; did you mean 'atomic_load_explicit'?
 1193 |     const auto ssl_ctx = std::atomic_load_excplicit(&ssl_context, std::memory_order_acquire);
      |                               ^~~~~~~~~~~~~~~~~~~~~
      |                               atomic_load_explicit

Reported-by: Frank Ederveen
Signed-off-by: Casey Bodley <cbodley@redhat.com>