mgr/dashboard: fix unable to create ingress unmanaged
the following snipped is the error from backend

```
 File "/lib/python3.6/site-packages/ceph/deployment/service_spec.py", line 698, in _from_json_impl
                                                  _cls.validate()
                                                File "/lib/python3.6/site-packages/ceph/deployment/service_spec.py", line 1058, in validate
                                                  'Cannot add ingress: No frontend_port specified')
                                              ceph.deployment.hostspec.SpecValidationError: Cannot add ingress: No frontend_port specified
```

It looks like even if we set unmanaged flag, we need to input the
backend_service, frontend_port, monitor_port and virtual_ip, because there is a
validation going for that in the backend.

https://github.com/ceph/ceph/blob/main/src/python-common/ceph/deployment/service_spec.py#L1050

Fixes: https://tracker.ceph.com/issues/57284
Signed-off-by: Nizamudeen A <nia@redhat.com>
(cherry picked from commit ea68560e148cf46dd69982120605519aba3a8955)