Revert "Merge pull request #8346 from yuyuyu101/wip-async-clock"
This reverts commit 005f7b6195fca0a885f1e452d929622a61b850e4, reversing
changes made to 3f24893242fa6e264b58b72435461344eef71286.

This broke the build:

msg/async/Event.cc: In member function 'int EventCenter::process_time_events()':
error: msg/async/Event.cc:280:30: cannot bind 'std::basic_ostream' lvalue to 'std::basic_ostream&&'
ldout(cct, 10) << __func__ << " cur time is " << now << dendl;
^

and elsewhere...

Signed-off-by: Sage Weil <sage@redhat.com>