cephadm: clean-up error message
use the standard error message from FileNotFound:
```
cephadm bootstrap --mon-ip 192.168.1.1 --config ~/foobar
ERROR: [Errno 2] No such file or directory: '/root/foobar'
```

Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit 870e9bddd2a059ae4930a2eed163bb862094dcaa)