rgw/driver/posix: s/is_value()/success()/
we have following build failure when building the tree:
```
 /home/kefu/dev/ceph/src/rgw/driver/posix/zpp_bits.h:3457:19: error: no member named 'is_value' in 'value_or_errc<Type>'
  3457 |         if (other.is_value()) {
       |             ~~~~~ ^
 In file included from /home/kefu/dev/ceph/src/rgw/driver/posix/rgw_sal_posix.cc:16:
 In file included from /home/kefu/dev/ceph/src/rgw/driver/posix/rgw_sal_posix.h:22:
```
it turns out the class of `value_or_errc` does not have the member
function of `is_value()`, so let's use `success()` instead.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>