ceph.spec.in: fix rpm package building error as follows:
      error: Installed (but unpackaged) file(s) found:
      /usr/lib/udev/rules.d/60-ceph-by-parttypeuuid.rules

Signed-off-by: runsisi <runsisi@zte.com.cn>
(cherry picked from commit 49dfad1f53d7abe0e9efc7817aaaf1735df5a9c9)