qa/tasks/test_nfs: have TestNFS inherit from CephFSTestCase
The TestNFS was recently updated to use run_ceph_cmd but
doesn't actually have access to it, resulting in

======================================================================
ERROR: test_cluster_info (tasks.cephfs.test_nfs.TestNFS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_ceph-c_4ae2a76aad461f2c9f6a1456c25df23ec97a5b2f/qa/tasks/cephfs/test_nfs.py", line 578, in test_cluster_info
    self._test_create_cluster()
  File "/home/teuthworker/src/git.ceph.com_ceph-c_4ae2a76aad461f2c9f6a1456c25df23ec97a5b2f/qa/tasks/cephfs/test_nfs.py", line 156, in _test_create_cluster
    cluster_create = self._nfs_complete_cmd(
  File "/home/teuthworker/src/git.ceph.com_ceph-c_4ae2a76aad461f2c9f6a1456c25df23ec97a5b2f/qa/tasks/cephfs/test_nfs.py", line 25, in _nfs_complete_cmd
    return self.run_ceph_cmd(args=f"nfs {cmd}", stdout=StringIO(),
AttributeError: 'TestNFS' object has no attribute 'run_ceph_cmd'

----------------------------------------------------------------------

The function we need is specified in the new RunCephCmd class,
which CephFSTestCase inherits from as well. We can't directly
inherit from RunCephCmd because that would skip the set up function
in CephFSTestCase which sets up the `mon_manager` attribute resulting in

File "<ceph-dir>/qa/tasks/cephfs/test_nfs.py", line 26, in _nfs_complete_cmd
    return self.run_ceph_cmd(args=f"nfs {cmd}", stdout=StringIO(),
File "<ceph-dir>/qa/tasks/cephfs/cephfs_test_case.py", line 58, in run_ceph_cmd
    return self.mon_manager.run_cluster_cmd(**kwargs)
AttributeError: 'NoneType' object has no attribute 'run_cluster_cmd'

Fixes: https://tracker.ceph.com/issues/62084

Signed-off-by: Adam King <adking@redhat.com>