container/Containerfile: fix crimson package naming
a37b5b5bde8c2e8d6890f16b31046119ed55f25d changed crimson-osd to
osd-crimson:

```
=== INSTALLING ===
No match for argument: ceph-crimson-osd
Error: Unable to find a match: ceph-crimson-osd
```

ceph-dev-pipeline builds are not failing (with the above error) -
however, ceph-dev-builds (used for main nightly) are failing with
the above:
https://shaman.ceph.com/builds/ceph/main/8a27bf16140173253ab8f28112bf5deee99cca02/

Signed-off-by: Matan Breizman <mbreizma@redhat.com>
(cherry picked from commit dac591543da506ad9be2f06c00c367e90ec1dd97)