os/seastore: fix FTBFS due to passing const d_node to _omap_set_kvs()
```
[ 96%] Building CXX object src/crimson/os/seastore/CMakeFiles/crimson-seastore.dir/seastore.cc.o
/home/jenkins-build/build/workspace/ceph-dev-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/19.0.0-1777-ga04996aa/rpm/el8/BUILD/ceph-19.0.0-1777-ga04996aa/src/crimson/os/seastore/seastore.cc: In lambda function:
/home/jenkins-build/build/workspace/ceph-dev-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/19.0.0-1777-ga04996aa/rpm/el8/BUILD/ceph-19.0.0-1777-ga04996aa/src/crimson/os/seastore/seastore.cc:1618:11: error: cannot convert ‘const OnodeRef’ {aka ‘const boost::intrusive_ptr<crimson::os::seastore::Onode>’} to ‘crimson::os::seastore::OnodeRef&’ {aka ‘boost::intrusive_ptr<crimson::os::seastore::Onode>&’}
 1618 |           d_onode,
      |           ^~~~~~~
      |           |
      |           const OnodeRef {aka const boost::intrusive_ptr<crimson::os::seastore::Onode>}
In file included from /home/jenkins-build/build/workspace/ceph-dev-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/19.0.0-1777-ga04996aa/rpm/el8/BUILD/ceph-19.0.0-1777-ga04996aa/src/crimson/os/seastore/seastore.cc:4:
/home/jenkins-build/build/workspace/ceph-dev-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/19.0.0-1777-ga04996aa/rpm/el8/BUILD/ceph-19.0.0-1777-ga04996aa/src/crimson/os/seastore/seastore.h:429:17: note:   initializing argument 1 of ‘crimson::os::seastore::SeaStore::Shard::omap_set_kvs_ret crimson::os::seastore::SeaStore::Shard::_omap_set_kvs(crimson::os::seastore::OnodeRef&, const crimson::os::seastore::omap_root_le_t&, crimson::os::seastore::Transaction&, std::map<std::__cxx11::basic_string<char>, ceph::buffer::v15_2_0::list>&&)’
  429 |       OnodeRef &onode,
      |       ~~~~~~~~~~^~~~~
make[2]: *** [src/crimson/os/seastore/CMakeFiles/crimson-seastore.dir/build.make:622: src/crimson/os/seastore/CMakeFiles/crimson-seastore.dir/seastore.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>