cmake: bump the required Boost version to 1.73
because ssl::host_name_verification was introduced in Asio 1.16.1 / Boost 1.73, and we
are using this class in src/librbd/migration/HttpClient.cc

This is an known error with Boost:
    https://cplusplus.github.io/LWG/issue3171

without this change, on a host with boost 1.72
it will complain (on FreeBSD/Clang):
```

/home/jenkins/workspace/ceph-master-compile/src/librbd/migration/HttpClient.cc:699:37: error: no member named 'host_name_verification' in namespace 'boost::asio::ssl'
      [host, next=boost::asio::ssl::host_name_verification(host),
                  ~~~~~~~~~~~~~~~~~~^
/home/jenkins/workspace/ceph-master-compile/src/librbd/migration/HttpClient.cc:714:16: error: no matching function for call to 'next'
        return next(preverified, ctx);
               ^~~~
```

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>