cmake: fix libcephfs linkage
The rename of TCMALLOC_LIBS to ALLOC_LIBS raced
with the CephFSVolumeClient pull request.

Fixes the following error:
ImportError: Unable to load libcephfs:
/home/john/ceph/build/src/libcephfs.so.1: undefined symbol:
IsHeapProfilerRunning

Signed-off-by: John Spray <john.spray@redhat.com>