test/objectstore/allocsim: Fix link error
I think this is another one that works by coincidence due to the optimizer.

```
/usr/bin/ld: CMakeFiles/replayer.dir/ops_replayer.cc.o: undefined reference to symbol '_ZN4ceph18__ceph_assert_failERKNS_11assert_dataE'
/usr/bin/ld: /home/lightspill/work/ceph/main/build/lib/libceph-common.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Signed-off-by: Adam C. Emerson <aemerson@redhat.com>