Bluestore: Add missing stubs for OSes not Linux
Otherwise the linker wil complain:

'''
usr/local/bin/x86_64-unknown-freebsd14.0-ld: /usr/local/bin/x86_64-unknown-freebsd14.0-ld: /usr/local/bin/x86_64-unknown-freebsd
14.0-ld: ../../lib/libblk.a(KernelDevice.cc.o): in function `KernelDevice::open(std::__1::basic_string<char, std::__1::char_trai
ts<char>, std::__1::allocator<char> > const&)':
/home/jenkins/workspace/ceph-master-compile/src/blk/kernel/KernelDevice.cc:236: undefined reference to `BlkDev::get_optimal_io_s
ize() const'
'''

Fixes: #43691
Fixes: https://tracker.ceph.com/issues/53483
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>