cephfs-shell: don't set use_ipython argument in super.__init__()
I get this traceback when trying to use cephfs-shell:

    Traceback (most recent call last):
      File "/usr/bin/cephfs-shell", line 1677, in <module>
        shell = CephFSShell()
      File "/usr/bin/cephfs-shell", line 389, in __init__
        super().__init__(use_ipython=False)
    TypeError: Cmd.__init__() got an unexpected keyword argument 'use_ipython'

The "use_ipython" argument has been renamed to "include_ipy". The
default for both of them is False though, so just drop the argument
altogether.

Signed-off-by: Jeff Layton <jlayton@redhat.com>