common,filestore: silence GCC-8 warnings
should catch polymorphic exceptions by reference. this silences warnings
like:

error: catching polymorphic type ‘class std::RetryException’ by value
[-Werror=catch-value=]
     } catch (std::RetryException) {

Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 62382040ee9b655a68b15ccb43cebb39c9dc3a45)