cmake: let ceph-client-debug link with tcmalloc
to fix the link problem of
libcephfs.so.1.0.0: undefined reference to `IsHeapProfilerRunning'
when tcmalloc is used and profiler header is detected.

Signed-off-by: Kefu Chai <kchai@redhat.com>