pybind/cephfs: Fix cython compilation error
cephfs.pyx:2324:40: Cannot assign type
'void (int, const void *, size_t, const void *, size_t, void *) except * nogil'

 to

'libcephfs_c_completion_t' (alias of 'void (*)(int, const void *, size_t, const void *, size_t, void *) noexcept nogil').

Introduced-by: 72d0a76e8c5cbb357e4f4c355e8630ec8aa02088
Signed-off-by: Kotresh HR <khiremat@redhat.com>