tests: Thrasher: eliminate a race between kill_osd and __init__
If Thrasher.__init__() spawns the do_thrash thread before initializing the
ceph_objectstore_tool property, do_thrash races with the rest
of Thrasher.__init__() and in some cases do_thrash can call kill_osd() before
Trasher.__init__() progresses much further. This can lead to an exception
("AttributeError: Thrasher instance has no attribute 'ceph_objectstore_tool'")
being thrown in kill_osd().

This commit eliminates the race by making sure the ceph_objectstore_tool
attribute is initialized before the do_thrash thread is spawned.

Fixes: http://tracker.ceph.com/issues/18799
Signed-off-by: Nathan Cutler <ncutler@suse.com>
(cherry picked from commit b519d38fb1967628ad8a1c46fcfb3f984de58790)

Conflicts:
    qa/tasks/ceph_manager.py (jewel has only one if statement after
        "self.thread = gevent.spawn(self.do_thrash)" while master has four;
        jewel lacks 66836c957ffd974dec136997e23261ec7de2f0aa which disables
        ceph-objectstore-tool testing in master)