qa/tasks/qemu: don't open text files in binary mode
This was causing failures under Python 3 since a bytes object
would be returned instead of the expected str:

	TypeError: sequence item 0: expected str instance, bytes found

Signed-off-by: Jason Dillaman <dillaman@redhat.com>