cmake: make libcap REQUIRED
this header is required when building the extended block device plugins
on linux, without it the build fails like:

```
/home/kefu/dev/ceph/src/extblkdev/ExtBlkDevInterface.h:38:10: fatal error: 'sys/capability.h' file not found
   38 | #include <sys/capability.h>
      |          ^~~~~~~~~~~~~~~~~~
```

so, let's mark this package REQUIRED, so that we can fail early
when generating the building system.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>