packaging: add missing dependency for ceph-volume
Typical error fixed:

```
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>