mds/{LocalLockC,SimpleLock}: un-inline methods using `MutationRef`
Commit e8bc28407117 added a forward declaration for `MutationRef` but
that doesn't work as long as the header constructs and destructs
instances, causing errors such as:

 build/debug/boost/include/boost/smart_ptr/intrusive_ptr.hpp: In instantiation of ‘boost::intrusive_ptr<T>::~intrusive_ptr() [with T = MutationImpl]’:
 src/mds/SimpleLock.h:424:5:   required from here
   424 |     ceph_assert(!get_xlock_by());
       |                  ~~~~~~~~~~~~^~
 build/debug/boost/include/boost/smart_ptr/intrusive_ptr.hpp:100:44: error: ‘intrusive_ptr_release’ was not declared in this scope; did you mean ‘ceph::common::intrusive_ptr_release’?
   100 |         if( px != 0 ) intrusive_ptr_release( px );
       |                       ~~~~~~~~~~~~~~~~~~~~~^~~~~~
       |                       ceph::common::intrusive_ptr_release

This never occurred previously because `Mutation.h` happened to be
already included by somebody else.

Signed-off-by: Max Kellermann <max.kellermann@ionos.com>