mgr/cephadm: fix RGWSpec mypy errors
cephadm/module.py:34: note: In module imported here:
cephadm/services/cephadmservice.py: note: In member "config" of class "RgwService":
cephadm/services/cephadmservice.py:167: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")

Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit bd6ea9c6a92ffbfa8676212b85d590e12decdbf5)