py3: cast dict_keys to list
Addresses:

  TypeError: 'dict_keys' object does not support indexing

and:

  RuntimeError: dictionary changed size during iteration

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>