build/ops: rpm: package crypto on x86_64 only
ca40e12845e78e507a0c3f45efa1689979029874 added the following lines to the spec
file:

%dir %{_libdir}/ceph/crypto
%{_libdir}/ceph/crypto/libceph_*.so*

and 350932979b377b292edd12dc8c612945cd793e7a made it so those build artifacts
are generated on x86_64 only.

The result is a build failure on non-x86_64 architectures:

error: Directory not found: /home/abuild/rpmbuild/BUILDROOT/ceph-12.0.2+git.1493119152.181baf6-1.1.ppc64le/usr/lib64/ceph/crypto
error: File not found by glob: /home/abuild/rpmbuild/BUILDROOT/ceph-12.0.2+git.1493119152.181baf6-1.1.ppc64le/usr/lib64/ceph/crypto/libceph_*.so*

Signed-off-by: Nathan Cutler <ncutler@suse.com>
(cherry picked from commit 4b79ac9a72c2ea71955fa6104f46818552b7a0b5)