common: Reorganize includes and template for FreeBSD
Obviously somewhere in the includes there is already an instantiation
for a conflicting type in the template:
```
/home/jenkins/workspace/ceph-master/src/common/lockdep.cc:21:12: error:
explicit specialization of 'std::__1::hash<pthread *>' after instantiation
   struct hash<pthread_t>
          ^~~~~~~~~~~~~~~
/usr/include/c++/v1/thread:269:16: note: implicit instantiation first
required here
       return hash<__libcpp_thread_id>()(__v.__id_);
              ^
```
And reshuffling fixes this. Could perhaps be fixed in the includes but
better not wait for that.

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>