cmake: link ceph_test_ino_release_cb with ceph-common
Fix linker failure when building with GCC-15 toolchain due to missing
ceph-common dependency.

The test executable uses internal MDS headers (mds/mdstypes.h and
fs_types.h) that reference buffer.h, creating an implicit dependency
on ceph-common symbols like ceph::buffer::v15_2_0::buffer_category().

While this worked with older toolchains, GCC-15's stricter linking
requirements exposed the missing dependency:

```
[2/3] Linking CXX executable bin/ceph_test_ino_release_cb
FAILED: bin/ceph_test_ino_release_cb
: && /usr/bin/c++ -O0 -g -fsanitize=address -fno-omit-frame-pointer -rdynamic -pie -Wl,--dependency-file=src/test/fs/CMakeFiles/ceph_test_ino_release_cb.dir/link.d src/test/fs/CMakeFiles/ceph_test_ino_release_cb.dir/test_ino_release_cb.cc.o -o bin/ceph_test_ino_release_cb  -Wl,-rpath,/home/kefu/dev/ceph/build/lib:  lib/libcephfs.so.2.0.0  -Wl,-rpath-link,/home/kefu/dev/ceph/build/lib  -Wl,--as-needed -latomic && :
/usr/bin/ld: src/test/fs/CMakeFiles/ceph_test_ino_release_cb.dir/test_ino_release_cb.cc.o: undefined reference to symbol '_ZN4ceph6buffer7v15_2_015buffer_categoryEv'
/usr/bin/ld: /home/kefu/dev/ceph/build/lib/libceph-common.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Fixed by explicitly linking ceph_test_ino_release_cb with ceph-common
to satisfy all symbol dependencies.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>