test/osd: Use shuffle instead of random_shuffle
This commit replaces std::random_shuffle with
std::shuffle.

The make check failed due to jenkins build failure :
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/osd/TestOSDMap.cc:2352:16: error: 'random_shuffle<__gnu_cxx::__normal_iterator<unsigned int *, std::vector<unsigned int>>>' is deprecated: use 'std::shuffle' instead [-Werror,-Wdeprecated-declarations]
          std::random_shuffle (osds.begin(), osds.end());
               ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_algo.h:4539:5: note: 'random_shuffle<__gnu_cxx::__normal_iterator<unsigned int *, std::vector<unsigned int>>>' has been explicitly marked deprecated here
    _GLIBCXX14_DEPRECATED_SUGGEST("std::shuffle")
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12/bits/c++config.h:112:45: note: expanded from macro '_GLIBCXX14_DEPRECATED_SUGGEST'
                                            ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12/bits/c++config.h:96:19: note: expanded from macro '_GLIBCXX_DEPRECATED_SUGGEST'
  __attribute__ ((__deprecated__ ("use '" ALT "' instead")))
                  ^
1 error generated.
```

Signed-off-by: Prashant D <pdhange@redhat.com>