CMakeLists: correct fmt version to fix compilation error
Compilation error is "error: 'group_digits' is not a member of 'fmt'".
As `fmt::group_digits` is added in fmt 8.1.0, if system's fmt version
is >= 7.0.0 but < 8.1.0, it wouldn't build and use system's fmt
instead, hence the error occurs. Correct the version here.

Fixes: https://tracker.ceph.com/issues/61857

Signed-off-by: luo rixin <luorixin@huawei.com>