teuthology/suite/matrix.py: Add item to assert msg
Give folks at least some hint about where things might
be broken:

```
AssertionError: Sum requires non-empty _submats: 0-distro
```

Signed-off-by: Sebastian Wagner <sewagner@redhat.com>