cephadm: Aquire lock, if fsid != None
Fixes:

```
Traceback (most recent call last):
  File "./cephadm", line 4494, in <module>
    r = args.func()
  File "./cephadm", line 1077, in _infer_fsid
    return func()
  File "./cephadm", line 1103, in _infer_image
    return func()
  File "./cephadm", line 2813, in command_ceph_volume
    l = FileLock(args.fsid)
  File "./cephadm", line 560, in __init__
    self._lock_file = os.path.join(LOCK_DIR, name + '.lock')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
(cherry picked from commit 2107649ffaf3d598a2d33cf94f40df1f91dff3c8)