rgw: need to give a type in list constructor
Clang complains about the missing type:
/home/jenkins/workspace/ceph-master/src/rgw/rgw_sync_module_es.cc:251:42: error: no viable constructor or deduction guide for deduction of template arguments of 'initializer_list'
  static constexpr std::initializer_list rgw_sys_attrs = {RGW_ATTR_PG_VER,
                                         ^
/usr/include/c++/v1/initializer_list:59:28: note: candidate function template not viable: requires 1 argument, but 7 were provided

Tried several type definitions, but this was the only one that make
Clang happy.

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>