ceph-volume: do not raise RuntimeError in util.lsblk
Otherwise it makes `simple scan` calls fail.

```
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 246, in lsblk
    raise RuntimeError(f"{device} not found is lsblk report")
RuntimeError: /var/lib/ceph/osd/ceph-0/ not found is lsblk report
```

Fixes: https://tracker.ceph.com/issues/58655

Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>
(cherry picked from commit 4f19a0f4e1726466968d610da3b0f753981e44a7)