mgr/dashboard: Make saml2 robust against module load errors
Loading saml2 can fail due to issues with the xmlsec package (possibly
subinterpreter related):

  File "/usr/share/ceph/mgr/dashboard/controllers/saml2.py", line 6, in <module>
    from onelogin.saml2.auth import OneLogin_Saml2_Auth
  File "/lib/python3.13/site-packages/onelogin/saml2/auth.py", line 12, in <module>
    import xmlsec
xmlsec.Error: (100, 'lxml & xmlsec libxml2 library version mismatch')

Instead of taking down the entire dashboard module, treat this exception
like a missing saml2 package.

Improves: https://tracker.ceph.com/issues/70411
Signed-off-by: Hector Martin <marcan@marcan.st>