mgr/cephadm: Proper error for OSErrors
Previsously, an OSError resulted in

    OSError: cannot send (already closed?)

which is not helpful.

Fixes: https://tracker.ceph.com/issues/45032
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
(cherry picked from commit 7540ab7ba0921fd48071c31fad8f8d8e4a887be7)