pybind/mgr: add urllib3==1.25.11 to mgr/requirements.txt
in hope to address the failure of

ERROR: Cannot install -r requirements.txt (line 3) and kubernetes because these package versions have conflicting dependencies.

The conflict is caused by:
    kubernetes 12.0.0 depends on urllib3>=1.24.2
    requests 2.24.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1

Signed-off-by: Kefu Chai <kchai@redhat.com>