rgw: Add more spawn linking
Signed-off-by: Daniel Gryniewicz <dang@redhat.com>
(cherry picked from commit 4ca4201b7fe3e0ca172548204b4b888a0908d162)
Signed-off-by: Mauricio Faria de Oliveira <mfo@canonical.com>

Conflicts:
        src/cls/CMakeLists.txt
        src/test/rgw/CMakeLists.txt

- Add spawn headers to includes to fix the two build errors below.
  No linking is needed since the files don't use 'spawn::' at all.

  In file included from /git/ceph/src/rgw/rgw_common.h:31:0,
                   from /git/ceph/src/cls/otp/cls_otp_client.cc:25:
  /git/ceph/src/common/async/yield_context.h:31:10: fatal error: spawn/spawn.hpp: No such file or directory
   #include <spawn/spawn.hpp>
            ^~~~~~~~~~~~~~~~~
  compilation terminated.
  src/cls/CMakeFiles/cls_otp_client.dir/build.make:62: recipe for target 'src/cls/CMakeFiles/cls_otp_client.dir/otp/cls_otp_client.cc.o' failed

  In file included from /git/ceph/src/rgw/rgw_dmclock_scheduler.h:21:0,
                   from /git/ceph/src/rgw/rgw_dmclock_sync_scheduler.h:18,
                   from /git/ceph/src/test/rgw/test_rgw_dmclock_scheduler.cc:17:
  /git/ceph/src/common/async/yield_context.h:31:10: fatal error: spawn/spawn.hpp: No such file or directory
   #include <spawn/spawn.hpp>
            ^~~~~~~~~~~~~~~~~
  compilation terminated.
  src/test/rgw/CMakeFiles/unittest_rgw_dmclock_scheduler.dir/build.make:62: recipe for target 'src/test/rgw/CMakeFiles/unittest_rgw_dmclock_scheduler.dir/test_rgw_dmclock_scheduler.cc.o' failed