rgw: use the forward declaration of CephContext defined in common_fwd.h
remove the ernonous redundant CephContext declaration

Clang complains:
In file included from /home/jenkins/workspace/ceph-master-compile/src/rgw/rgw_lua_utils.cc:5:
/home/jenkins/workspace/ceph-master-compile/src/rgw/rgw_lua_utils.h:8:1: error: declaration conflicts with target of using declaration already in scope
class CephContext;
^
/home/jenkins/workspace/ceph-master-compile/src/include/common_fwd.h:10:9: note: target of using declaration
  class CephContext;
        ^
/home/jenkins/workspace/ceph-master-compile/src/include/common_fwd.h:22:24: note: using declaration
using TOPNSPC::common::CephContext;

Which is more that correct.

To declare CephContext forward, include common_fwd.h.
But this was already included in the hierarcy.

fixes: https://github.com/ceph/ceph/pull/35477
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>