debian: add libkrb5-dev to Build-Depends
install_deps.sh on Ubuntu 24.04 fails with an error
       subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.
because on 24.04 the package krb5-config no longer
provides headers and libs for gssapi, those are now
provided by libkrb5-dev

Fixes: https://tracker.ceph.com/issues/80240
Signed-off-by: Edwin Rodriguez <edwin.rodriguez1@ibm.com>