mgr/cephadm: make setting --cgroups=split configurable
Previously, we were just always setting this as long
as users were using podman with a high enough version,
but it seems a user has run into an issue where their
daemons are failing to deploy with

Error: could not find cgroup mount in "/proc/self/cgroup"

despite having a podman with high enough version.

Fixes: https://tracker.ceph.com/issues/57096

Signed-off-by: Adam King <adking@redhat.com>
(cherry picked from commit c57cb0b236e27a1d475aa8eb397ef7b880024bf5)

Conflicts:
	src/pybind/mgr/cephadm/module.py