test/objectstore: include missing headerfile for get_csum_type_string
Otherwise during linking there is no matching definition:
[ 88%] Linking CXX executable ../../../bin/unittest_bluestore_types
/usr/local/bin/ld: CMakeFiles/unittest_bluestore_types.dir/test_bluestore_types.cc.o: in function `bluestore_blob_t_csum_bench_Test::TestBody()':
/home/jenkins/workspace/ceph-master-compile/src/test/objectstore/test_bluestore_types.cc:332: undefined reference to `std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::operator<< <long long, std::__1::ratio<1l, 1000000000l> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&)'

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>