cephadm: add log warn when unable to infer mon ip addr
fixup for `--mon-ip` bootstrap test (introduced 31874b8):
  ValueError: 'eth0' does not appear to be an IPv4 or IPv6 address

Signed-off-by: Michael Fritch <mfritch@suse.com>