cephadm: show error when no command is specified
Traceback (most recent call last):
  File "./cephadm", line 4452, in <module>
    if args.func != command_check_host:
AttributeError: 'Namespace' object has no attribute 'func'

Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit 2ebb9373b52342eb8c523866e5852d2b8bf44e58)