install-deps.sh: Install python headers on openSUSE/SLE
When installing python modules from source, the python headers are
needed when the module needs to compile code. This is eg. needed for
xmlsec. Without Python.h available, ./install-deps.sh fails with:

/tmp/pip-wheel-Kx6zVj/xmlsec/src/platform.h:16:10: \
    fatal error: Python.h: No such file or directory

Fixes: https://tracker.ceph.com/issues/42665

Signed-off-by: Thomas Bechtold <tbechtold@suse.com>